### ISSUE TITLE
Receiving an invalid sensortype error that is killing the process/container

### ISSUE THREAD

**Issue by shauder** [dariopb/gosense#1]
I am receiving this on both of my dongles now after this. It seems to kill the docker container and it goes into a restart loop. One of the dongles has never had any sensors paired with it.

`ha-gosenseapp starting...
time="2019-10-20T19:52:22Z" level=error msg="not a valid SensorType: \"0\""`

**Comment by dariopb** [comment]
Fixed with https://github.com/dariopb/gosense/commit/fcc5776311c5db97ee2d17705ade85a867d98ae4. Thanks.
