### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by dgmltn** [dariopb/gosense#2]
Is this project still in development/maintenance? It's working swimmingly for me, for window/door sensors and motion sensors. I'm just wondering if you'll add support for the other sensor types when & if they ever release them.

**Comment by dariopb** [comment]
Hi, yes, I'll definitely add support for other sensor types if/when they release them for this "gw". The code is working fine for me with a dozen or so sensors as well.

**Comment by dgmltn** [comment]
Great to hear! Thanks! 👍
